<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Philiprehberger.RandomReadableString</PackageId>
    <Version>0.1.2</Version>
    <Authors>Philip Rehberger</Authors>
    <Description>Generate human-readable random strings like "sunny-falcon-42"</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/philiprehberger/dotnet-random-readable-string</RepositoryUrl>
    <PackageTags>random;string;readable;generator;identifier</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
